wifi:
  fast_connect: true
  networks:
  - ssid: iot master
    password: !secret minimal_wifi_network1_password
    manual_ip:
      static_ip: 192.168.31.101
      gateway: 192.168.30.1
      subnet: 255.255.254.0
      dns1: 192.168.30.1
      dns2: 1.1.1.1
  domain: !secret domain
  ap:
    ssid: minimal
    password: !secret wifi_network1_password
    ap_timeout: 1min

captive_portal:


esp8266:
  board: esp8285
  restore_from_flash: true

esphome:
  name: minimal8266
  name_add_mac_suffix: false

preferences:
  flash_write_interval: 1min

api:

ota:
  - platform: esphome

logger:
  level: INFO
  baud_rate: 115200


web_server:
  port: 80